# Generated by Django 5.1.7 on 2025-03-29 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
            ],
        ),
        migrations.AlterField(
            model_name='word_freq',
            name='word',
            field=models.CharField(max_length=255),
        ),
        migrations.AddField(
            model_name='word_freq',
            name='file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_freqs', to='testapp.uploadedfile'),
        ),
        migrations.AlterUniqueTogether(
            name='word_freq',
            unique_together={('file', 'word')},
        ),
    ]
