# Generated by Django 5.1.7 on 2025-03-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_uploadedfile_alter_word_freq_word_word_freq_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word_freq',
            name='freq',
        ),
        migrations.AddField(
            model_name='word_freq',
            name='tf',
            field=models.FloatField(default=0),
        ),
    ]
