# Generated by Django 5.1.7 on 2025-03-30 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_remove_word_freq_freq_word_freq_tf'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Word_freq',
        ),
    ]
