# Generated by Django 5.1.7 on 2025-03-30 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_delete_word_freq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
