# Generated by Django 5.1.7 on 2025-06-01 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tfidf_data', models.JSONField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('max_time_processed', models.FloatField(blank=True, null=True)),
                ('min_time_processed', models.FloatField(blank=True, null=True)),
                ('avg_word_count', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ProcessedFile',
        ),
        migrations.AddField(
            model_name='filemetrics',
            name='uploaded_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='testapp.uploadedfile'),
        ),
    ]
