# Generated by Django 5.1.7 on 2025-06-07 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_filemetrics_uploadedfile_delete_processedfile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileMetrics',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
