# Generated by Django 5.1.7 on 2025-06-11 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='word_statistics', to='core.collection'),
        ),
    ]
